### ISSUE TITLE
AddPdfFileName

### ISSUE THREAD

**Issue by cerdts** [uppercuut/TemplateToPdf.Demo#2]
The generated PDF filename is always "ById.pdf" regardless of what is contained in the .AddPdfFileName("Filename") method. This can be observed in the Demo based on the TheStarterKit.

**Comment by cerdts** [comment]
Name:
  wkhtmltopdf 0.12.6 (with patched qt)

Synopsis:
  wkhtmltopdf [GLOBAL OPTION]... [OBJECT]... <output file>

**Comment by IbrahimMNada** [comment]
Hello there , 

the issue is fixed now. 

Install-Package Our.Umbraco.TemplateToPdf -Version 1.0.10

**Comment by cerdts** [comment]
Thank you
